### ISSUE TITLE
Install process

### ISSUE THREAD

**Issue by buxx** [buxx/tracim#1]
With Ubuntu 14.04 and python3**.4**:

At step:

```
virtualenv -p /usr/bin/python3 tg2env
source tg2env/bin/activate
cd tracim && python setup.py develop && cd -
pip install -r install/requirements.txt
./bin/tg2env-patch 1 tg2env/lib/python3.2/site-packages
pip install -r install/requirements.txt
./bin/tg2env-patch 2 tg2env/lib/python3.2/site-packages
```

Execution of 

```
virtualenv -p /usr/bin/python3 tg2env
source tg2env/bin/activate
cd tracim && python setup.py develop && cd -
```

was ok.

On first `pip install -r install/requirements.txt`:

```
[...]
  File "/home/bsevajol/projects/tracim/tg2env/build/wsgiref/ez_setup/__init__.py", line 170

    print "Setuptools version",version,"or greater has been installed."

                             ^

SyntaxError: invalid syntax
```

Then, `./bin/tg2env-patch 1 tg2env/lib/python3.4/site-packages`:

```
[...]
RefactoringTool: Can't open tg2env/lib/python3.4/site-packages/babel: [Errno 2] No such file or directory: 'tg2env/lib/python3.4/site-packages/babel'
-> done
Patching code in file tg2env/lib/python3.4/site-packages/babel/messages/pofile.py...
(Patch is indented 4 spaces.)
patching file tg2env/lib/python3.4/site-packages/babel/messages/pofile.py
Hunk #1 FAILED at 384.
patch: **** Can't reopen file tg2env/lib/python3.4/site-packages/babel/messages/pofile.py : No such file or directory
-> done
```

Then, second `pip install -r install/requirements.txt` produce:

```
[...]
    import ez_setup

  File "/home/bsevajol/projects/tracim/tg2env/build/wsgiref/ez_setup/__init__.py", line 170

    print "Setuptools version",version,"or greater has been installed."

                             ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
```

Then `./bin/tg2env-patch 2 tg2env/lib/python3.4/site-packages`:

```
PATCHING PYTHON CODE
--------------------
site packages path:    tg2env/lib/python3.4/site-packages

Patching code in file tg2env/lib/python3.4/site-packages/resetpassword/lib/__init__.py...
sed: impossible de lire tg2env/lib/python3.4/site-packages/resetpassword/lib/__init__.py: Aucun fichier ou dossier de ce type
-> done
```

Database configuration done, access test ok.

When execute `gearbox setup-app`:

`zsh: command not found: gearbox`

So, gearbox installed with `pip install gearbox`

```
Successfully installed PasteDeploy-1.5.2 PrettyTable-0.7.2 PyYAML-3.11 Tempita-0.5.2 argparse-1.4.0 cliff-1.15.0 cmd2-0.6.8 gearbox-0.0.9 pbr-1.8.1 pyparsing-2.0.5 six-1.10.0 stevedore-1.9.0 unicodecsv-0.14.1
```

Then, `gearbox setup-app` produce:

```
Failed to load project commands with error "tg.devtools", have you installed your project?
13:49:51,137 ERROR [gearbox] No module named 'tgext'
```

**Comment by lebouquetin** [comment]
Here is a raw documentation that should work with python 3.4 : 

---

Installation
J'ai repris tout le process d'install sur une debian jessie vierge histoire d'être sûr de ne pas te dire de bêtises.

Voici les modifs à faire dans la procédure :

Avant tout, modifier le fichier install/requirement.txt :
- supprimer la ligne "wsgiref"
- modifier la version de "tgext.pluggable" pour avoir la 0.5.4 au lieu de la 0.5.2
  (fichier modifié en pièce jointe)

Ensuite, suivre la procédure normale, sauf pour la phase "setting-up python virtualenv", pour laquelle les étapes à suivre sont les suivantes :

source tg2env/bin/activate
cd tracim/ && python setup.py develop && cd -
pip install -r install/requirements.txt
./bin/tg2env-patch 1 tg2env/lib/python3.4/site-packages
./bin/tg2env-patch 2 tg2env/lib/python3.4/site-packages

On utilise pyvenv au lieu de virtualenv (pyvenv est la version python3.4 de virtualenv)

Enfin, pour la configuration, vu que tu travailles sur une machine virtuelle, penses à mettre host = 0.0.0.0 (par défaut on est sur 127.0.0.1 donc tu n'auras pas accès à Tracim depuis ton poste de travail.

Tout le reste est identique.

Je vais mettre à jour la doc sur Github.

**Comment by buxx** [comment]
Thank's, i will try with this and update this issue.

**Comment by lebouquetin** [comment]
Note : if you want a raw install process working for sure you can also check the travis install process (which is run just before unit tests) : see https://github.com/buxx/tracim/blob/master/.travis.yml

(note : it's a know issue that pip install -r requirements.txt returns errors, that's why the travis install step is "pip install -r install/requirements.txt; echo" (note the echo, which returns 0 as execution status code).

But with python 3.4, it should install without errors

**Comment by buxx** [comment]
All worked fine!

![selection_200](https://cloud.githubusercontent.com/assets/1104637/10912549/544ed3ee-824a-11e5-942e-f9641c4b13ce.png)

**Comment by lebouquetin** [comment]
Did you install with python 3.4 or python 3.2 ? (or other) ? anything to update on the documentation ?

**Comment by buxx** [comment]
Installed with python 3.4. Modifying install/requirement.txt like said in [this](https://github.com/buxx/tracim/issues/1#issuecomment-153382243) comment was sufficient to proceed pip install and patchs. README can be update for python 3.4 in this way (i make a pull request ?)

**Comment by lebouquetin** [comment]
Yes a pull request would be fine !
